// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.js");
var Route = require("./Route.js");
var Today = require("./Today.js");
var React = require("react");
var Header = require("./Header.js");
var Overall = require("./Overall.js");

function App(Props) {
  var route = Route.useRoute(undefined);
  var verticalAlign = CssJs.style([
        CssJs.height({
              NAME: "vh",
              VAL: 100
            }),
        CssJs.display("flex"),
        CssJs.flexDirection(CssJs.column)
      ]);
  return React.createElement("div", {
              className: verticalAlign
            }, React.createElement(Header.make, {}), route ? React.createElement(Today.make, {}) : React.createElement(Overall.make, {}));
}

var make = App;

exports.make = make;
/* CssJs Not a pure module */
