// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-dom/src/CssJs.js");
var React = require("react");
var Future = require("rescript-future/src/Future.js");
var $$Request = require("rescript-request/src/Request.js");
var Css_Js_Core = require("bs-css/src/Css_Js_Core.js");

var card = CssJs.style([
      CssJs.display(CssJs.flexBox),
      CssJs.flexDirection(CssJs.column),
      CssJs.alignItems(CssJs.stretch),
      CssJs.backgroundColor(CssJs.white),
      CssJs.boxShadow(Css_Js_Core.Shadow.box(undefined, CssJs.px(3), CssJs.px(5), undefined, undefined, CssJs.rgba(0, 0, 0, {
                    NAME: "num",
                    VAL: 0.3
                  })))
    ]);

var title = CssJs.style([
      CssJs.fontSize(CssJs.rem(1.5)),
      CssJs.color(CssJs.black),
      CssJs.marginBottom(CssJs.px(4))
    ]);

var Styles = {
  card: card,
  title: title
};

function App(Props) {
  console.log("doing request");
  Future.get($$Request.make("/books", undefined, /* JsonAsAny */5, undefined, undefined, undefined, undefined, undefined, undefined, undefined), (function (prim) {
          console.log(prim);
          
        }));
  return React.createElement("div", {
              style: card
            }, React.createElement("div", {
                  style: title
                }, "Hello World"));
}

var make = App;

exports.Styles = Styles;
exports.make = make;
/* card Not a pure module */
