// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./Link.js");
var CssJs = require("bs-css-emotion/src/CssJs.js");
var React = require("react");

var header = CssJs.style([
      CssJs.display("flex"),
      CssJs.padding(CssJs.px(16))
    ]);

var link = CssJs.style([CssJs.marginLeft(CssJs.px(8))]);

var Styles = {
  header: header,
  link: link
};

function Header(Props) {
  return React.createElement("div", {
              className: header
            }, React.createElement(Link.make, {
                  className: link,
                  onClick: Link.$$location(Link.overall),
                  children: "Overall"
                }), React.createElement(Link.make, {
                  className: link,
                  onClick: Link.$$location(Link.today),
                  children: "Today"
                }));
}

var make = Header;

exports.Styles = Styles;
exports.make = make;
/* header Not a pure module */
