// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Caml_option = require("rescript/lib/js/caml_option.js");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.js");

function customFn(fn) {
  return {
          TAG: /* CustomFn */1,
          _0: fn
        };
}

function $$location($$location$1) {
  return {
          TAG: /* Location */0,
          _0: $$location$1
        };
}

var push = RescriptReactRouter.push;

function handleClick(onClick, $$event) {
  if (onClick.TAG === /* Location */0) {
    $$event.preventDefault();
    RescriptReactRouter.push(onClick._0);
  } else {
    Curry._1(onClick._0, undefined);
  }
  
}

var activeClass = "active";

function Link(Props) {
  var classNameOpt = Props.className;
  var styleOpt = Props.style;
  var onClick = Props.onClick;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var style = styleOpt !== undefined ? Caml_option.valFromOption(styleOpt) : ({});
  var match = RescriptReactRouter.useUrl(undefined, undefined);
  var isActive;
  isActive = onClick.TAG === /* Location */0 ? onClick._0.toLowerCase().includes(match.hash.toLowerCase()) : false;
  var href;
  href = onClick.TAG === /* Location */0 ? onClick._0 : undefined;
  var tmp = {
    className: isActive ? className + (" " + activeClass) : className,
    style: style,
    onClick: (function (param) {
        return handleClick(onClick, param);
      })
  };
  if (href !== undefined) {
    tmp.href = Caml_option.valFromOption(href);
  }
  return React.createElement("a", tmp, children);
}

function Link$Button(Props) {
  var classNameOpt = Props.className;
  var styleOpt = Props.style;
  var onClick = Props.onClick;
  var disabledOpt = Props.disabled;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var style = styleOpt !== undefined ? Caml_option.valFromOption(styleOpt) : ({});
  var disabled = disabledOpt !== undefined ? disabledOpt : false;
  return React.createElement("button", {
              className: className,
              style: style,
              disabled: disabled,
              onClick: (function (param) {
                  return handleClick(onClick, param);
                })
            }, children);
}

var Button = {
  make: Link$Button
};

var overall = "/#/overall";

var today = "/#/today";

var make = Link;

exports.customFn = customFn;
exports.$$location = $$location;
exports.overall = overall;
exports.today = today;
exports.push = push;
exports.handleClick = handleClick;
exports.activeClass = activeClass;
exports.make = make;
exports.Button = Button;
/* react Not a pure module */
