// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Future = require("rescript-future/src/Future.js");
var $$Request = require("rescript-request/src/Request.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function resolveRequest(request, cb) {
  return Future.get(request, (function (resolved) {
                if (resolved.TAG === /* Ok */0) {
                  var response = resolved._0.response;
                  if (response !== undefined) {
                    return Curry._1(cb, Caml_option.valFromOption(response));
                  } else {
                    console.log("could not parse response");
                    return ;
                  }
                }
                console.log("request error", resolved._0);
                
              }));
}

var make = $$Request.make;

exports.resolveRequest = resolveRequest;
exports.make = make;
/* No side effect */
