// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var $$Request = require("rescript-request/src/Request.js");
var ResponseMapper = require("./ResponseMapper.js");

var overallProgressContainer = CssJs.style([
      CssJs.textAlign(CssJs.center),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 400
          }),
      CssJs.margin(CssJs.px(64))
    ]);

var header = CssJs.style([
      CssJs.padding2(CssJs.px(12), CssJs.px(20)),
      CssJs.marginBottom(CssJs.px(0)),
      CssJs.backgroundColor(CssJs.rgba(0, 0, 0, {
                NAME: "num",
                VAL: 0.03
              })),
      CssJs.border(CssJs.px(1), CssJs.solid, CssJs.rgba(0, 0, 0, {
                NAME: "num",
                VAL: 0.125
              })),
      CssJs.borderRadius4(CssJs.px(3), CssJs.px(3), CssJs.px(0), CssJs.px(0))
    ]);

var Styles = {
  overallProgressContainer: overallProgressContainer,
  header: header
};

function Today(Props) {
  var match = React.useState(function () {
        return 1;
      });
  var setProgress = match[1];
  React.useEffect((function () {
          ResponseMapper.resolveRequest($$Request.make("/progress/calculate", "POST", /* JsonAsAny */5, undefined, undefined, undefined, undefined, undefined, undefined, undefined), (function (response) {
                  return Curry._1(setProgress, (function (param) {
                                return response;
                              }));
                }));
          
        }), []);
  return React.createElement("div", {
              className: overallProgressContainer
            }, "sa books");
}

var make = Today;

exports.Styles = Styles;
exports.make = make;
/* overallProgressContainer Not a pure module */
