// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./Link.js");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.js");

function useRoute(param) {
  var match = RescriptReactRouter.useUrl(undefined, undefined);
  switch (match.hash) {
    case "/books" :
        return /* Books */1;
    case "/challenge" :
        return /* Challenge */0;
    default:
      Link.push(Link.books);
      return /* Books */1;
  }
}

exports.useRoute = useRoute;
/* Link Not a pure module */
